# Generated by Django 5.2.8 on 2026-09-03 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnstileGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. Main Turnstile 01', max_length=128)),
                ('ip_address', models.GenericIPAddressField(help_text='Local TCP/IP relay controller IP')),
                ('port', models.PositiveIntegerField(default=5000)),
                ('relay_pin', models.PositiveIntegerField(default=1)),
                ('pulse_duration_ms', models.PositiveIntegerField(default=300)),
                ('is_online', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.CharField(db_index=True, max_length=64)),
                ('member_name', models.CharField(max_length=255)),
                ('entry_method', models.CharField(choices=[('dynamic_qr', '15s Dynamic QR Code'), ('assisted_staff', 'Front-Desk Assisted Check-in'), ('nfc_card', 'NFC / RFID Card'), ('usb_barcode', 'USB Barcode Reader')], default='dynamic_qr', max_length=32)),
                ('verified_hmac', models.BooleanField(default=True)),
                ('assisted_reason', models.CharField(blank=True, help_text='Mandatory if assisted_staff', max_length=255, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=64, null=True)),
                ('offline_buffered', models.BooleanField(default=False)),
                ('gate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='pulse.turnstilegate')),
            ],
            options={
                'indexes': [models.Index(fields=['gym_id', 'member_id', 'created_at'], name='pulse_check_gym_id_f864cd_idx')],
            },
        ),
    ]
