# Generated by Django 5.2.8 on 2026-09-03 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPhotoRecognitionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.CharField(max_length=64)),
                ('image_url', models.URLField()),
                ('stage_1_vision_output', models.JSONField(help_text='Detected food labels from multimodal model')),
                ('stage_2_verified_macros', models.JSONField(help_text='Matched macros against USDA FoodData API')),
                ('confidence_score', models.DecimalField(decimal_places=3, default=0.95, max_digits=4)),
                ('user_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('serving_size_grams', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('calories', models.PositiveIntegerField()),
                ('protein_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_usda_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.CharField(db_index=True, max_length=64)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=16)),
                ('servings', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('logged_date', models.DateField(db_index=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.fooditem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
