# Generated by Django 5.2.8 on 2026-09-03 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('member_id', models.CharField(db_index=True, max_length=64)),
                ('member_name', models.CharField(max_length=255)),
                ('member_phone', models.CharField(max_length=32)),
                ('plan_code', models.CharField(max_length=64)),
                ('months_extended', models.PositiveIntegerField(default=1)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, help_text='18% CGST + SGST', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='upi', max_length=32)),
                ('payment_gateway_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Payment Verified & Pass Extended'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('gateway', models.CharField(default='razorpay', max_length=32)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GSTInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sac_code', models.CharField(default='999723', help_text='SAC 999723 Fitness Center Services', max_length=16)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('invoice_pdf_url', models.URLField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pay.membershiporder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
