# Generated by Django 5.2.8 on 2026-09-03 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.CharField(db_index=True, max_length=64)),
                ('member_name', models.CharField(max_length=255)),
                ('member_phone', models.CharField(max_length=32)),
                ('plan_name', models.CharField(max_length=128)),
                ('days_absent', models.PositiveIntegerField(db_index=True)),
                ('risk_tier', models.CharField(choices=[('tier_1', '10–14 Days (Early Risk)'), ('tier_2', '15–21 Days (Moderate Risk)'), ('tier_3', '22+ Days (Critical Churn Danger)')], db_index=True, default='tier_1', max_length=16)),
                ('potential_revenue_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('locked_by_staff_id', models.CharField(blank=True, max_length=64, null=True)),
                ('locked_by_staff_name', models.CharField(blank=True, max_length=128, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetentionOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_id', models.CharField(db_index=True, help_text="Tenant UUID or 'kynvelo-direct' for B2C", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.CharField(max_length=64)),
                ('staff_name', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('whatsapp', '1-Tap WhatsApp Deep-Link'), ('phone_call', 'Direct Phone Call'), ('in_person', 'Front-Desk Discussion')], default='whatsapp', max_length=16)),
                ('status', models.CharField(choices=[('returning_soon', 'Will return this week'), ('travelling', 'Travelling (Frozen Pass)'), ('injured', 'Injured / Medical Recovery'), ('dropping_out', 'Considering dropping out (Offered coach review)'), ('no_response', 'Unreachable / Left voicemail')], max_length=32)),
                ('internal_notes', models.TextField(blank=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='flow.inactivitycase')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
